import os

def fix_text(text):
    replacements = {
        'SÃ¡Â»â€˜': 'Số',
        'tiÃ¡Â»Â n': 'tiền',
        'nÃ¡ÂºÂ¡p': 'nạp',
        'tÃ¡Â»â€˜i': 'tối',
        'thiÃ¡Â»Æ’u': 'thiểu',
        'lÃƒÂ ': 'là',
        'vÃƒÂ ': 'và',
        'Ã„â€˜a': 'đa',
        'KhÃƒÂ´ng': 'Không',
        'tÃƒÂ¬m': 'tìm',
        'thÃ¡ÂºÂ¥y': 'thấy',
        'ngÃ†Â°Ã¡Â»Â i': 'người',
        'dÃƒÂ¹ng': 'dùng',
        'ChÃ¡ÂºÂ·n': 'Chặn',
        'giao': 'giao',
        'dÃ¡Â»â€¹ch': 'dịch',
        'nÃ¡ÂºÂ¿u': 'nếu',
        'vÃƒÂ­': 'ví',
        'Ã„â€˜ang': 'đang',
        'bÃ¡Â»â€¹': 'bị',
        'tÃ¡ÂºÂ¡m': 'tạm',
        'khÃƒÂ³a': 'khóa',
        'CÃ¡ÂºÂ­p': 'Cập',
        'nhÃ¡ÂºÂ­t': 'nhật',
        'sÃ¡Â»â€˜': 'số',
        'dÃ†Â°': 'dư',
        'Ghi': 'Ghi',
        'nhÃ¡ÂºÂ­n': 'nhận',
        'thÃƒÂ nh': 'thành',
        'cÃƒÂ´ng': 'công',
        'LÃ¡Â»â€”i': 'Lỗi',
        'Theo': 'Theo',
        'dÃƒÂµi': 'dõi',
        'kÃ¡ÂºÂ¿t': 'kết',
        'quÃ¡ÂºÂ£': 'quả',
        'tÃ¡Â»Â«': 'từ',
        'bÃ¡ÂºÂ£ng': 'bảng',
        'ThiÃ¡ÂºÂ¿u': 'Thiếu',
        'tham': 'tham',
        'bÃ¡ÂºÂ¯t': 'bắt',
        'buÃ¡Â»â„¢c': 'buộc',
        'Ã„Â Ã¡Â»â€¹nh': 'Định',
        'dÃ¡ÂºÂ¡ng': 'dạng',
        'ngÃƒÂ y': 'ngày',
        'yÃƒÂªu': 'yêu',
        'cÃ¡ÂºÂ§u': 'cầu',
        'Ã„Â Ã†Â°Ã¡Â»Â ng': 'Đường',
        'dÃ¡ÂºÂ«n': 'dẫn',
        'hÃ¡Â»Â£p': 'hợp',
        'lÃ¡Â»â€¡': 'lệ',
        'ÃƒÆ’Ã¢â‚¬Å¾Ãƒâ€šÃ‚Â ÃƒÆ’Ã¢â‚¬Â Ãƒâ€šÃ‚Â°ÃƒÆ’Ã‚Â¡Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â ng': 'Đường',
        'dÃƒÆ’Ã‚Â¡Ãƒâ€šÃ‚ÂºÃƒâ€šÃ‚Â«n': 'dẫn',
        'khÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â´ng': 'không',
        'hÃƒÆ’Ã‚Â¡Ãƒâ€šÃ‚Â»Ãƒâ€šÃ‚Â£p': 'hợp',
        'lÃƒÆ’Ã‚Â¡Ãƒâ€šÃ‚Â»ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¡': 'lệ',
        'MÃƒÂ£': 'Mã',
        'rÃ¡ÂºÂ¡p': 'rạp',
        'phÃ¡ÂºÂ£i': 'phải',
        'nguyÃƒÂªn': 'nguyên',
        'dÃ†Â°Ã†Â¡ng': 'dương',
        'trang': 'trang',
        'lÃ¡Â»â€ºn': 'lớn',
        'hÃ†Â¡n': 'hơn',
        'hoÃ¡ÂºÂ·c': 'hoặc',
        'bÃ¡ÂºÂ±ng': 'bằng',
        'KÃƒÂ­ch': 'Kích',
        'thÃ†Â°Ã¡Â»â€ºc': 'thước',
        'nÃ¡ÂºÂ±m': 'nằm',
        'trong': 'trong',
        'khoÃ¡ÂºÂ£ng': 'khoảng',
        'Ã„â€˜Ã¡ÂºÂ¿n': 'đến',
        'giÃƒÂ¡': 'giá',
        'trÃ¡Â»â€¹': 'trị',
        'phim': 'phim',
        'Ã„â€˜Ã†Â°Ã¡Â»Â£c': 'được',
        'Ã„â€˜Ã¡Â»Æ’': 'để',
        'trÃ¡Â»â€˜ng': 'trống',
        'TÃ¡Â»Â«': 'Từ',
        'kiÃ¡ÂºÂ¿m': 'kiếm',
        'vÃ†Â°Ã¡Â»Â£t': 'vượt',
        'quÃƒÂ¡': 'quá',
        'kÃƒÂ½': 'ký',
        'tÃ¡Â»Â±': 'tự',
        'TrÃ¡ÂºÂ¡ng': 'Trạng',
        'thÃƒÂ¡i': 'thái',
        'VÃ¡Â»â€¹': 'Vị',
        'trÃƒÂ­': 'trí',
        'phÃƒÂ¢n': 'phân',
        'giÃ¡Â»â€ºi': 'giới',
        'hÃ¡ÂºÂ¡n': 'hạn',
        'cho': 'cho',
        'phÃƒÂ©p': 'phép',
        'lá»': 'lọc',
        'YÃªu': 'Yêu',
        'cáº§u': 'cầu',
        'khÃ´ng': 'không',
        'há»£p': 'hợp',
        'lá»‡': 'lệ',
        'pháº£i': 'phải',
        'lá»›n': 'lớn',
        'hÆ¡n': 'hơn',
        'hoáº·c': 'hoặc',
        'báº±ng': 'bằng',
        'tá»«': 'từ',
        'Ä‘áº¿n': 'đến',
        'Thiáº¿u': 'Thiếu',
        'báº¯t': 'bắt',
        'buá»™c': 'buộc',
        'Sá»‘': 'Số'
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text

def process_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    new_content = fix_text(content)
    if new_content != content:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f'Fixed mojibake in {path}')

for root, _, files in os.walk(r'f:\ltw\cinema\src\main\java\com\cinema'):
    for file in files:
        if file.endswith('.java'):
            process_file(os.path.join(root, file))
